### ISSUE TITLE
Statusline statement breaks the statusline in Macvim

### ISSUE THREAD

**Issue by fatih** [ewilazarus/preto#2]
Hi,

The two lines:

```
call s:HL('StatusLine'    , s:palette.white , s:palette.black , 'none'     )
call s:HL('StatusLineNC'  , s:palette.white , s:palette.black , 'none'     )
```

breaks the statusline in MacVim. Examples:

![image](https://cloud.githubusercontent.com/assets/438920/13032640/f5c965aa-d302-11e5-9769-5b5275b5900d.png)

![image](https://cloud.githubusercontent.com/assets/438920/13032641/f96d9410-d302-11e5-928f-58dbc5f143ad.png)

It works perfectly for Vim and NeoVim though. I've disabled them myself.

**Comment by ewilazarus** [comment]
Hey there, thanks for pointing that out!

I created a branch named 'macvim' and pushed [a fix](https://github.com/ewilazarus/preto/commit/efb2d15436e2d009d0283086efbdd41451f741a2) for it. However, I can't test it here - do you mind testing it yourself and telling me if it works, so I can close this issue?

**Comment by fatih** [comment]
Works perfect :+1: Solves all two problems of mines :) Now the contrast for comments and co are a little bit to high for how I like it, but I can change it myself ;) Thanks!

**Comment by ewilazarus** [comment]
Good If you feel like it, fork the project and send a pull request with your modifications
